#!/bin/sh

alias shgen="echo '#!/bin/sh' > "

shgen /bin/jakup
chmod +x /bin/jakup
echo "/workspaces/fun-unfun-notation/jakup" >> /bin/jakup
echo ". /workspaces/fun-unfun-notation/runvenv" > /bin/runvenv
